export const WORDS: string[] = [
  // A compact starter list of common 5-letter words (expand as needed)
  "ABOUT","OTHER","WHICH","THEIR","THERE","FIRST","WOULD","THESE","CLICK","BROWN","GREEN","GRAPE","PLANT","SHARE","SMILE","BRAVE","CRANE","SLATE","TRACE","SLICE","PRIDE","PRIDE","BRICK","WRONG","RIGHT","HEART","SMART","SWEET","SUGAR","HONEY","MONEY","WATER","WORLD","EARTH","MUSIC","MOVIE","BOOKS","STONE","STEEL","BLINK","BRING","SOUND","LIGHT","NIGHT","ROUND","GUESS","WORDS","FRESH","TRUST","TRIAL","ALERT","ALONE","ANGEL","BASIC","BEACH","BLACK","BLADE","CANDY","CHESS","CLOUD","COVER","CROSS","CROWN","DANCE","DAILY","DELTA","DRIVE","DREAM","ELITE","ENTRY","FAITH","FAIRY","FANCY","FARMS","FAVOR","FIBER","FIELD","FLAME","FLEET","FRUIT","GIANT","GLASS","GRACE","GRAND","GRASS","GROUP","HAPPY","HONEY","HOUSE","HUMAN","IMAGE","INDEX","INNER","JELLY","JOLLY","JUICE","KNIFE","LABEL","LASER","LEMON","LEVEL","LIGHT","MAGIC","MAJOR","METAL","MINOR","MOTOR","NOBLE","NORTH","NOVEL","OCEAN","OLIVE","ONION","OPERA","PAINT","PAUSE","PEACH","PEARL","PIANO","PIZZA","PLAIN","PLANE","PLANT","PRIZE","QUEEN","QUEST","QUIET","RADIO","RANGE","READY","RIVER","ROBOT","SALAD","SCENE","SCOPE","SHEEP","SHELF","SHINE","SHIRT","SHOCK","SKILL","SMALL","SMOKE","SNAKE","SOLID","SPACE","SPOON","SPORT","STAMP","STEAM","STORM","SUGAR","TEACH","TEETH","THING","THINK","THOSE","TIGER","TITLE","TOAST","TOOTH","TOUCH","TOUGH","TOWER","TRUCK","TRUST","UNION","UNITE","URBAN","VALUE","VIDEO","VIRUS","VISIT","WHEAT","WHEEL","WHITE","WOMAN","WOMEN","YOUTH","ZEBRA"
];

export function randomWords(count: number): string[] {
  const set = new Set<string>();
  while (set.size < count) {
    const w = WORDS[Math.floor(Math.random() * WORDS.length)];
    set.add(w);
  }
  return Array.from(set).slice(0, count);
}

